module.exports = {
  parser: 'babel-eslint',
  plugins: [
    'sitegenesis',
  ],
  extends: [
    'airbnb-base',
    '@jenssimon/base',
  ],
  env: {
    commonjs: true,
    es6: true,
    browser: false,
  },
  globals: {
    dw: true,
    customer: true,
    session: true,
    request: true,
    response: true,
    empty: true,
    PIPELET_ERROR: true,
    PIPELET_NEXT: true,
    global: true,
    webreferences: true,
    webreferences2: true,
    APIException: true,
    ConversionError: true,
    Fault: true,
    IOError: true,
    Iterator: true,
    QName: true,
    StopIteration: true,
    SystemError: true,
    XML: true,
    XMLList: true,
    XMLStreamError: true,
  },
  rules: {
    'comma-dangle': ['error', {
      arrays: 'always-multiline',
      objects: 'always-multiline',
      imports: 'always-multiline',
      exports: 'always-multiline',
      functions: 'never',
    }],
    'consistent-return': 'off',
    'global-require': 'off',
    'import/no-unresolved': 'off',
    'import/no-extraneous-dependencies': 'off',
    'import/no-dynamic-require': 'off',
    'new-cap': 'off',
    'no-var': 'off',
    'no-restricted-globals': 'off',
    'object-shorthand': 'off',
    'prefer-arrow-callback': 'off',
    'prefer-const': 'off',
    'prefer-destructuring': 'off',
    'prefer-rest-params': 'off',
    'prefer-spread': 'off',
    'prefer-template': 'off',
    strict: 'off',
  },
  overrides: [
    {
      files: [
        '**/controllers/**',
      ],
      rules: {
        'sitegenesis/no-global-require': ['error'],
      },
    },
  ],
};
