module.exports = {
  dw: true,
  customer: true,
  session: true,
  request: true,
  response: true,
  empty: true,
  PIPELET_ERROR: true,
  PIPELET_NEXT: true,
  global: true,
  webreferences: true,
  webreferences2: true,
  APIException: true,
  ConversionError: true,
  Fault: true,
  IOError: true,
  Iterator: true,
  QName: true,
  StopIteration: true,
  SystemError: true,
  XML: true,
  XMLList: true,
  XMLStreamError: true,
}
