name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js
      uses: actions/setup-node@v5
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn

    - name: Lint
      run: yarn lint

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v5
        - uses: actions/setup-node@v5
          with:
            node-version-file: .nvmrc
            cache: 'yarn'
        - name: Release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          run: |
            yarn
            npx semantic-release
