name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: ".node-version"
          cache: true

      - name: Check
        run: vp check

      - name: Test
        run: vp test

      - name: Pack
        run: vp pack

      - name: Release
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: vp exec semantic-release
